[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang = "2.0.0"
cmake = "0.1.51"
llvm = "0.0.1"
openssl = "0.10.68"
pkg-config = "0.3.31"
